#!/usr/bin/bash
# Thu Mar 26, 2020 18:43
# Page 330 of epdf The Linux Command Line
# template of sys_info_page script

# add variables
TITLE="System Information For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"
AUTHOR="Author: $USER"

# Fri 27 Mar 2020 09:40:41 PM +03
# create 3 functions to use in main script below

report_uptime () {
  # note the dash after the double arrow of here doc
  # this allows tab formatting for readability (but not spaces)
  cat <<- _EOF_
  			<h2>System Uptime</h2>
			<pre>$(uptime)</pre>
			_EOF_
  #echo "Function report_uptime executed."
  return
}

report_disk_space () {
  cat <<- _EOF_
  			<h2>Disk Space Utilization</h2>
			<pre>$(df -h)</pre>
			_EOF_
  #echo "Function report_disk_space executed."
  return
}

report_home_space () {
  if [[ "$(id -u)" -eq 0 ]]; then
	echo "You are root, welcome dear master!"
	cat <<- _EOF_
		<h2>Home Space Utilization (All Users)</h2>
		<pre>$(du -sh /home/*)</pre>
		_EOF_
	else
	cat <<- _EOF_
		<h2>Home Space Utilization ($USER)</h2>
		<pre>$(du -sh "$HOME")</pre>
		_EOF_
  fi
  return
  #echo "Function report_home_space executed."
}

# using echo and variables defined above.
#<head>
#  <title>$TITLE</title>
#</head>
#<body>
#  <h1>$TITLE</h1>
#  <p>$TIMESTAMP</p>
#  <p>$AUTHOR</p>
#</body>
#</html>"

# another version using here document
cat << _EOF_
<html>
  <head>
	<title>$TITLE</title>
  </head>
  <body>
	<h1>$TITLE</h1>
	<p>$TIMESTAMP</p>
	<p>$AUTHOR</p>
	$(report_home_space)
	$(report_uptime)
	$(report_disk_space)
  </body>
</html>
_EOF_
